# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import mdt_dialout_pb2 as mdt__dialout__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mdt_dialout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class gRPCMdtDialoutStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MdtDialout = channel.stream_stream(
                '/mdt_dialout.gRPCMdtDialout/MdtDialout',
                request_serializer=mdt__dialout__pb2.MdtDialoutArgs.SerializeToString,
                response_deserializer=mdt__dialout__pb2.MdtDialoutArgs.FromString,
                _registered_method=True)


class gRPCMdtDialoutServicer:
    """Missing associated documentation comment in .proto file."""

    def MdtDialout(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPCMdtDialoutServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MdtDialout': grpc.stream_stream_rpc_method_handler(
                    servicer.MdtDialout,
                    request_deserializer=mdt__dialout__pb2.MdtDialoutArgs.FromString,
                    response_serializer=mdt__dialout__pb2.MdtDialoutArgs.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mdt_dialout.gRPCMdtDialout', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mdt_dialout.gRPCMdtDialout', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class gRPCMdtDialout:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MdtDialout(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mdt_dialout.gRPCMdtDialout/MdtDialout',
            mdt__dialout__pb2.MdtDialoutArgs.SerializeToString,
            mdt__dialout__pb2.MdtDialoutArgs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
